#![allow(clippy::tests_outside_test_module)]
#![allow(clippy::unwrap_used)]
//! Parity tests: `riri-npd` + `riri-yarn::YarnLock` must produce the exact pins
//! the legacy JS `@smarlhens/npm-pin-dependencies@0.11.x` asserts for yarn v1
//! and berry v2. Inputs and expected outputs are copied verbatim from that
//! package's `tests/pin-from-string.spec.ts` ("yarn lock v1" / "yarn lock v2").
//!
//! These also exercise the classic parser's handling of nested `dependencies:`
//! sub-blocks and comma-joined transitive descriptors (`fake-package-4`), which
//! must NOT leak into the root pin set.

use riri_common::PackageJson;
use riri_npd::{DependencyKind, pin_dependencies};
use riri_yarn::YarnLock;

const PKG: &str = r#"{"name":"fake","private":true,"dependencies":{"fake-package-1":"^1.0.0","fake-package-2":"^2.0.0","fake-package-3":"^3.0.0"}}"#;

const YARN_V1: &str = "# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1
fake-package-1@^1.0.0:
  version \"1.0.3\"
  resolved \"https://registry.npmjs.org/fake-package-1/-/fake-package-1-1.0.3.tgz#hash\"
fake-package-2@^2.0.0:
  version \"2.0.1\"
  resolved \"https://registry.npmjs.org/fake-package-2/-/fake-package-2-2.0.1.tgz#hash\"
  dependencies:
    fake-package-4 \"^4.0.0\"
fake-package-3@^3.0.0:
  version \"3.1.9\"
  resolved \"https://registry.npmjs.org/fake-package-3/-/fake-package-3-3.1.9.tgz#hash\"
  dependencies:
    fake-package-4 \"^4.5.0\"
fake-package-4@^4.0.0, fake-package-4@^4.5.0:
  version \"4.6.3\"
  resolved \"https://registry.npmjs.org/fake-package-4/-/fake-package-4-4.6.3.tgz#hash\"";

const YARN_V2: &str = "# This file is generated by running \"yarn install\" inside your project.
# Manual changes might be lost - proceed with caution!

__metadata:
  version: 4

\"fake-package-1@npm:^1.0.0\":
  version: 1.0.3

\"fake-package-2@npm:^2.0.0\":
  version: 2.0.1
  dependencies:
    \"fake-package-4\": \"^4.0.0\"

\"fake-package-3@npm:^3.0.0\":
  version: 3.1.9
  dependencies:
    \"fake-package-4\": \"^4.5.0\"

\"fake-package-4@npm:^4.0.0, fake-package-4@npm:^4.5.0\":
  version: 4.6.3
";

/// `(name, from-range, pinned-version)` — the legacy JS `versionsToPin` set.
const EXPECTED: [(&str, &str, &str); 3] = [
    ("fake-package-1", "^1.0.0", "1.0.3"),
    ("fake-package-2", "^2.0.0", "2.0.1"),
    ("fake-package-3", "^3.0.0", "3.1.9"),
];

fn assert_parity(lock_content: &str) {
    let pkg: PackageJson = serde_json::from_str(PKG).unwrap();
    let lock = YarnLock::parse(lock_content).unwrap();
    let pins = pin_dependencies(&pkg, &lock).unwrap();

    assert_eq!(pins.len(), EXPECTED.len(), "pins: {pins:?}");
    for (pin, (name, from, to)) in pins.iter().zip(EXPECTED) {
        assert_eq!(pin.name, name);
        assert_eq!(pin.kind, DependencyKind::Dependencies);
        assert_eq!(pin.current_range, from);
        assert_eq!(pin.pinned_version, to);
    }
    // Transitive-only `fake-package-4` must never be pinned (not a root dep).
    assert!(pins.iter().all(|p| p.name != "fake-package-4"));
}

#[test]
fn matches_legacy_js_yarn_lock_v1() {
    assert_parity(YARN_V1);
}

#[test]
fn matches_legacy_js_yarn_lock_v2_berry() {
    assert_parity(YARN_V2);
}
