repos:
  - repo: https://github.com/pre-commit/pre-commit
    rev: "v3.8.0"
    hooks:
      - id: validate_manifest

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.6.0"
    hooks:
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v4.0.0-alpha.8"
    hooks:
      - id: prettier

  - repo: local
    hooks:
      - id: fmt
        name: fmt
        description: Format files with cargo fmt.
        entry: cargo fmt --all -- --check
        language: rust
        types: [rust]
        pass_filenames: false
      - id: cargo-check
        name: cargo check
        description: Check the package for errors.
        entry: cargo check
        language: rust
        types: [rust]
        pass_filenames: false
      - id: clippy
        name: clippy
        entry: cargo clippy --all-targets
        language: rust
        args: ["--", "-D", "warnings"]
        types: [rust]
        pass_filenames: false
