[package]
name = "riri-node-tools"
version = "0.1.0"
edition = "2021"
authors = ["Samuel MARLHENS <samuel.marlhens@proton.me>"]
license-file = "LICENSE"

[[bin]]
name = "pin-dependencies"
path = "src/pin-dependencies.rs"

[[bin]]
name = "check-engines"
path = "src/check-engines.rs"

[dependencies]
anyhow = "1.0.89"
clap = { version = "4.5.21", features = ["derive"] }
clap-verbosity-flag = "2.2.2"
comfy-table = "7.1.1"
console = "0.15.8"
detect-indent = "0.1.0"
log = "0.4.22"
regex = "1.11.0"
semver = "1.0.23"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = { version = "1.0.128", features = ["preserve_order"] }
serde_yml = "0.0.12"
tracing = "0.1.40"
tracing-log = "0.2.0"
tracing-subscriber = "0.3.18"

[lints.clippy]
pedantic = "deny"
dbg_macro = "deny"
empty_structs_with_brackets = "deny"
float_cmp_const = "deny"
if_then_some_else_none = "deny"
same_name_method = "deny"
tests_outside_test_module = "deny"
unseparated_literal_suffix = "deny"
unwrap_used = "deny"
