[package]
name = "riri-napi-ncd"
version = "0.1.3"
description = "Find deprecated packages in the lockfile dependency tree"
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { workspace = true }
napi-derive = { workspace = true }
riri-ncd = { path = "../riri-ncd", version = "0.2.0", default-features = false, features = ["cli"] }

[build-dependencies]
napi-build = { workspace = true }

[lints]
workspace = true
