[package]
name = "riri-find-up"
version = "0.1.1"
description = "Walk up the directory tree to find files"
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dev-dependencies]
tempfile = { workspace = true }

[lints]
workspace = true
