#![allow(clippy::tests_outside_test_module)]
#![allow(clippy::unwrap_used)]
//! Unit tests for the `YarnLock` parser — resolves versions by `name@range`
//! descriptor, mirroring the old JS `@smarlhens/npm-pin-dependencies` behavior.
//! Covers classic v1 (custom format) and berry v2+ (syml/YAML).

use riri_common::LockfileVersions;
use riri_yarn::YarnLock;

const CLASSIC_V1: &str = r#"# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


foo@^4.17.21:
  version "4.17.21"
  resolved "https://registry.yarnpkg.com/foo/-/foo-4.17.21.tgz#placeholder"
  integrity sha512-placeholder

bar@~18.2.0:
  version "18.2.0"
  resolved "https://registry.yarnpkg.com/bar/-/bar-18.2.0.tgz#placeholder"

baz@^1.0.0, baz@^1.2.0:
  version "1.6.0"
  resolved "https://registry.yarnpkg.com/baz/-/baz-1.6.0.tgz#placeholder"

"@scope/qux@^2.0.0":
  version "2.3.4"
  resolved "https://registry.yarnpkg.com/@scope/qux/-/qux-2.3.4.tgz#placeholder"
"#;

const BERRY: &str = r#"# This file is generated by running "yarn install" inside your project.
# Manual changes might be lost - proceed with caution!

__metadata:
  version: 8
  cacheKey: 10

"foo@npm:^4.17.21":
  version: 4.17.21
  resolution: "foo@npm:4.17.21"
  checksum: placeholder
  languageName: node
  linkType: hard

"bar@npm:~18.2.0":
  version: 18.2.0
  resolution: "bar@npm:18.2.0"

"baz@npm:^1.0.0, baz@npm:^1.2.0":
  version: 1.6.0
  resolution: "baz@npm:1.6.0"

"@scope/qux@npm:^2.0.0":
  version: 2.3.4
  resolution: "@scope/qux@npm:2.3.4"
"#;

#[test]
fn classic_resolves_caret_range_to_version() {
    let lock = YarnLock::parse(CLASSIC_V1).unwrap();
    assert_eq!(lock.resolved_version("foo", "^4.17.21"), Some("4.17.21"));
}

#[test]
fn classic_resolves_tilde_range() {
    let lock = YarnLock::parse(CLASSIC_V1).unwrap();
    assert_eq!(lock.resolved_version("bar", "~18.2.0"), Some("18.2.0"));
}

#[test]
fn classic_resolves_comma_joined_descriptor_each_range() {
    let lock = YarnLock::parse(CLASSIC_V1).unwrap();
    assert_eq!(lock.resolved_version("baz", "^1.0.0"), Some("1.6.0"));
    assert_eq!(lock.resolved_version("baz", "^1.2.0"), Some("1.6.0"));
}

#[test]
fn classic_resolves_quoted_scoped_descriptor() {
    let lock = YarnLock::parse(CLASSIC_V1).unwrap();
    assert_eq!(lock.resolved_version("@scope/qux", "^2.0.0"), Some("2.3.4"));
}

#[test]
fn classic_unknown_range_is_none() {
    let lock = YarnLock::parse(CLASSIC_V1).unwrap();
    // Right name, wrong range → no descriptor match (faithful to old JS).
    assert_eq!(lock.resolved_version("foo", "^9.9.9"), None);
    assert_eq!(lock.resolved_version("missing", "^1.0.0"), None);
}

#[test]
fn berry_resolves_via_npm_descriptor() {
    let lock = YarnLock::parse(BERRY).unwrap();
    assert_eq!(lock.resolved_version("foo", "^4.17.21"), Some("4.17.21"));
    assert_eq!(lock.resolved_version("bar", "~18.2.0"), Some("18.2.0"));
}

#[test]
fn berry_resolves_comma_joined_and_scoped() {
    let lock = YarnLock::parse(BERRY).unwrap();
    assert_eq!(lock.resolved_version("baz", "^1.0.0"), Some("1.6.0"));
    assert_eq!(lock.resolved_version("baz", "^1.2.0"), Some("1.6.0"));
    assert_eq!(lock.resolved_version("@scope/qux", "^2.0.0"), Some("2.3.4"));
}

#[test]
fn berry_skips_metadata_block() {
    let lock = YarnLock::parse(BERRY).unwrap();
    // `__metadata` must not leak in as a resolvable descriptor.
    assert_eq!(lock.resolved_version("__metadata", "8"), None);
}

/// Build a berry lock for a given `__metadata.version`, reproducing the format
/// each real version emits. md4-8 use bare checksums; md9+ prefix them with the
/// cache key (`10/…`), quote nested protocols (`"npm:…"`), and can carry
/// non-npm `link:` locators with URL-encoded references and `0.0.0-use.local`
/// versions — all of which must parse without choking the resolver.
fn berry_lock_for(version: u32, cache_key: &str) -> String {
    let (sum, dep_proto, extra_entry) = if version >= 9 {
        (
            "10/abc123",
            "\"npm:^1.0.0\"",
            // A real md9 babel-style link: locator — must parse, never panic.
            "\n\"$repo-utils@link:./scripts/repo-utils::locator=babel%40workspace%3A.\":\n  version: 0.0.0-use.local\n  resolution: \"$repo-utils@link:./scripts/repo-utils::locator=babel%40workspace%3A.\"\n  languageName: node\n  linkType: soft\n",
        )
    } else {
        ("abc123", "1.0.0", "")
    };
    format!(
        "# This file is generated by running \"yarn install\" inside your project.\n\
         # Manual changes might be lost - proceed with caution!\n\n\
         __metadata:\n  version: {version}\n  cacheKey: {cache_key}\n\
         {extra_entry}\n\
         \"foo@npm:^4.17.21\":\n  version: 4.17.21\n  resolution: \"foo@npm:4.17.21\"\n  \
         dependencies:\n    bar: {dep_proto}\n  checksum: {sum}\n  languageName: node\n  linkType: hard\n\n\
         \"@scope/bar@npm:~18.2.0\":\n  version: 18.2.0\n  resolution: \"@scope/bar@npm:18.2.0\"\n  \
         checksum: {sum}\n  languageName: node\n  linkType: hard\n\n\
         \"baz@npm:^1.0.0, baz@npm:^1.2.0\":\n  version: 1.6.0\n  resolution: \"baz@npm:1.6.0\"\n  \
         checksum: {sum}\n  languageName: node\n  linkType: hard\n"
    )
}

/// Every `__metadata.version` real Yarn Berry releases have ever emitted, with
/// the yarn release line that produced it (verified by fetching `yarn.lock`
/// from `yarnpkg/berry` at each tag). The parser must resolve all of them — the
/// version-distinguishing fields (`checksum` prefix, `conditions`/libc, quoted
/// protocols) are exactly the ones it ignores.
const REAL_BERRY_VERSIONS: &[(u32, &str)] = &[
    (4, "7"),   // yarn 2.4.x, 3.0.x
    (5, "8"),   // yarn 3.1.x
    (6, "8"),   // yarn 3.4.x–3.8.x
    (7, "9"),   // yarn 4.0.0-rc.x
    (8, "10"),  // yarn 4.0.x–4.1.x
    (9, "10"),  // yarn 4.x (later)
    (10, "10"), // yarn berry master
];

#[test]
fn berry_resolves_across_every_real_metadata_version() {
    for &(version, cache_key) in REAL_BERRY_VERSIONS {
        let content = berry_lock_for(version, cache_key);
        let lock = YarnLock::parse(&content)
            .unwrap_or_else(|e| panic!("metadata v{version} failed to parse: {e}"));

        assert_eq!(
            lock.resolved_version("foo", "^4.17.21"),
            Some("4.17.21"),
            "metadata v{version}: regular npm descriptor"
        );
        assert_eq!(
            lock.resolved_version("@scope/bar", "~18.2.0"),
            Some("18.2.0"),
            "metadata v{version}: scoped descriptor"
        );
        assert_eq!(
            lock.resolved_version("baz", "^1.0.0"),
            Some("1.6.0"),
            "metadata v{version}: first range of comma-joined descriptor"
        );
        assert_eq!(
            lock.resolved_version("baz", "^1.2.0"),
            Some("1.6.0"),
            "metadata v{version}: second range of comma-joined descriptor"
        );
    }
}
