[package]
name = "parser"
version = "0.1.0"
edition = "2021"
authors.workspace = true
license-file.workspace = true

[dependencies]
core = { path = "../core" }
serde_json = "1.0.111"
serde_yaml = "0.9.30"
regex = "1.10.2"

[lints]
workspace = true
