[package]
name = "riri-lockfile"
version = "0.1.1"
description = "Parse any supported Node.js lockfile from a string, without touching the filesystem"
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[features]
scan = ["riri-yarn/scan"]
graph = [
    "riri-common/graph",
    "riri-npm/graph",
    "riri-pnpm/graph",
    "riri-yarn/graph",
]

[dependencies]
riri-common = { path = "../riri-common", version = "0.2.0" }
riri-npm = { path = "../riri-npm", version = "0.2.0" }
riri-pnpm = { path = "../riri-pnpm", version = "0.2.0" }
riri-yarn = { path = "../riri-yarn", version = "0.1.5" }
thiserror = { workspace = true }

[dev-dependencies]
rstest = { workspace = true }
tempfile = { workspace = true }

[lints]
workspace = true
