[package]
name = "finder"
version = "0.1.0"
edition = "2021"
authors.workspace = true
license-file.workspace = true

[dependencies]
definitely-typed = { path = "../definitely-typed" }

[lints]
workspace = true
