[package]
name = "check-engines"
version = "0.1.0"
edition = "2021"
authors.workspace = true
license-file.workspace = true

[dependencies]
finder = { path = "../finder" }
parser = { path = "../parser" }

[lints]
workspace = true
