name: actionlint

on:
  push:
    branches: ["main"]
    paths:
      - ".github/workflows/**"
      - ".github/actions/**"
      - ".github/actionlint.yaml"
  pull_request:
    branches: ["**"]
    paths:
      - ".github/workflows/**"
      - ".github/actions/**"
      - ".github/actionlint.yaml"

permissions: {}

jobs:
  actionlint:
    name: Run actionlint
    runs-on: ubuntu-24.04
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Run actionlint
        uses: docker://rhysd/actionlint:1.7.12
        with:
          args: -color -shellcheck=
