name: ci

on:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        toolchain:
          - stable
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Install Rust
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - name: Check formatting
        run: cargo fmt --all --manifest-path Cargo.toml -- --check
      - name: Check errors
        run: cargo check
      - name: Lint
        run: cargo clippy --all-targets --manifest-path Cargo.toml
      - name: Build
        run: cargo build --verbose
      - name: Test
        run: cargo test --verbose
