name: publish-npd

on:
  release:
    types: [created]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  napi:
    if: ${{ github.event_name == 'workflow_dispatch' || startsWith(github.event.release.tag_name, 'npm-pin-dependencies-') }}
    uses: ./.github/workflows/napi.yml
    permissions:
      contents: read
      id-token: write
    with:
      crate-dir: crates/riri-napi-npd
      app-name: npm-pin-dependencies
      run-publish: true
